### ISSUE TITLE
I get a blank screen after login

### ISSUE THREAD

**Issue by FadyM** [ipragmatech/Android-Magento-Rest-Api-Integration#2] opened 2016-06-16 12:33 UTC
Error while loading asset assets/natives_blob_64.bin: java.io.FileNotFoundException: assets/natives_blob_64.bin

Error while loading asset assets/snapshot_blob_64.bin: java.io.FileNotFoundException: assets/snapshot_blob_64.bin

com.google.api.client.http.HttpResponseException: 404 Not Found

Full error log is attached 

[Errorlog.txt](https://github.com/ipragmatech/Android-Magento-Rest-Api-Integration/files/318354/Errorlog.txt)

**Comment by manish-ip** [comment] 2016-06-20 05:03
Hello FadyM,

We have re-tested our code it's working fine from our side. Can you please recheck your code because as far as we understood from your error log that you are able to login into the site but there is some data from your site is missing that is why it is throwing "file not found" exception . For more details you can refer to our blog : 
[Magento mobile rest API](http://www.ipragmatech.com/magento-mobile-app-rest-api/)

**Comment by FadyM** [comment] 2016-06-26 13:19
Hello Manish 

Thank you for your response ...
I guess it the issue is related to the magneto version .. I was using version 2.0 ..
I have installed another instance now 1.9

I get the error 

06-26 15:13:02.814 24627-25116/com.ipragmatech.oauthmagentogoogle E/OAuthMagentoRetrofit: 400 Bad Request
                                                                                          oauth_problem=parameter_absent&oauth_parameters_absent=oauth_verifier
                                                                                          com.google.api.client.http.HttpResponseException: 400 Bad Request
                                                                                          oauth_problem=parameter_absent&oauth_parameters_absent=oauth_verifier


The error occurs when trying to call accessToken.execute() the screen displays the logon page for a second then it redirect to a blank page ... not quite sure what to do though 


Thank you,
FadyM

**Comment by nehaprakash** [comment] 2016-06-27 07:56
Hi FadyM,
I am Neha from iPragmatech , I have integrated this functionality in our app so from now I will take over this issue. As I have gone through your issue, it seems that there is some problem in your store configuration authentication setting. Please cross check  your store setting for REST API roles, attributes and keys.

If still, the issue exists, please provide us your site credentials at neha.prakash@ipragmatech.com, so that we can find the issue and help you to solve it.

Thank you,
Neha

**Comment by FadyM** [comment] 2016-06-27 08:33
Hello Neha,

Thank you for your response .. I have rechecked the configuration and couldn't find anything 
Credentials are sent via email ... Thank you so much really appreciated your help

Thank you,
Fady

**Comment by navyon** [comment] 2016-06-28 10:17
I have also tried to test this, I believe all keys are correct but when I log in I got a blank screen as well. I am using Magento 1.9.2.   

Thanks

**Comment by nehaprakash** [comment] 2016-06-28 10:24
Hi Navyon,
The problem is with OAUTH_CALLBACK_URL. You don't need to change it, leave it to localhost i.e. "http://localhost/".

**Comment by navyon** [comment] 2016-06-28 10:29
I still get the blank screen when I change the URL to http://localhost/  , is it suppose to load the products ?

**Comment by nehaprakash** [comment] 2016-06-29 05:44
Hi Navyon,
I checked your issue using your credential and in response I am getting response 404 Not found. It seems that your baseurl is not working with your api and it is working on browser so,it may be configuration issue for the web services. Please check your configuration setting for the Web Services  REST  roles and Oauth settings.

**Comment by nehaprakash** [comment] 2016-06-29 06:06
Hello FadyM,
The problem is with your OAUTH_CALLBACK_URL it should be like "http://localhost/magento" because your magento is installed at that path, instead of "http://localhost". If you will use "http://localhost" as callbackurl then u need to install your magento into localhost rather than keeping it into some other sub directory i.e magento in your case. 

Thanks,
Neha

**Comment by navyon** [comment] 2016-06-29 06:20
Hi Neha,

I have already configured those settings,  I have just emailed you credentials to the admin. It works using firefox Rest client, but not with the app.

**Comment by nehaprakash** [comment] 2016-06-29 08:23
Hi Young,

I looked your issue and it seems that the problem is in your Host server configuration. Our sample is working for our store and for others users also. Please, check your hosting server setting or you can take paid support from our support team. They will help you in resolving the issues.

**Comment by navyon** [comment] 2016-06-29 09:02
Hi Neha,

Thanks for your help I have just changed the host configuration to allow in the root directory. But the blank screen remains. with the 404 error

<Directory /var/www/html/magento/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

**Comment by navyon** [comment] 2016-06-29 09:22
Hello Neha, 

I have found the issue because I am using store views, I have to also add the store view URL in the base url.  This can be useful for others.

Thanks  for your help..

**Closed** 2016-07-06 06:27 UTC
